version: '3.1'


services:
  db:
    container_name: database
    image: postgres
    env_file:
      - ".env"
    environment:
      POSTGRES_PASSWORD: $PASSWORD_DB
      POSTGRES_USER: $USER_DB
      POSTGRES_DB: $NAME_DB
    restart: always
    ports:
     - 5432
    networks:
      - botnet
    volumes:
      - ./postgresql:/var/lib/postgresql

  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    volumes:
      - .:/src
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db
      - django
 
  django:
    container_name: djangoproject
    build:
      context: .
    command: python django_app.py runserver 0.0.0.0:8000 --noreload
    ports:
      - 8000:8000
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db


# указываются используемые сети
networks:
  botnet:

    driver: bridge
