# Generated by Django 4.0.4 on 2022-07-10 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0008_alter_purchase_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanage.item', verbose_name='Идентификатор товара'),
        ),
    ]
