# Generated by Django 4.0.4 on 2022-08-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanage', '0009_alter_purchase_item_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='botadmin',
            options={'verbose_name': 'Админ бота', 'verbose_name_plural': 'Админы бота'},
        ),
        migrations.AlterField(
            model_name='user',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Бонусные баллы'),
        ),
    ]
